data:
  json_public_path_train: "data/keypoints/public_data/train"
  json_public_path_val: "data/keypoints/public_data/val"
  json_private_path_train: "data/keypoints/private_data/train"
  json_private_path_val: "data/keypoints/private_data/val"
  is_public: false # Public is true hoặc Private is false
  max_frame: 100    # Số frame tối đa
  batch_size: 32     # Kích thước batch

mlflow:
  name_id: "Thesis25"
  artifact_location: "../../ai_model_capstone/Thesis_25_artifact"
  run_name: "finetune_test_gcn" # or GCN_test

model:
  model_name: "gcn"  # "spoter" hoặc "gcn"
  pretrained: false  # Pretrained is true hay is false

  pretrain_config:
    spoter:
      num_classes: 10
      hidden_dim: 72
      num_heads: 9
      encoder_layers: 1
      decoder_layers: 1 

    gcn:
      in_channels: 3
      hidden_dim: 128
      num_classes: 10
      
  finetune_config:
    spoter:
      num_classes: 4
      hidden_dim: 72
      num_heads: 9
      encoder_layers: 1
      decoder_layers: 1    

    gcn:
      in_channels: 3
      hidden_dim: 128
      num_classes: 4

train:
  num_epochs: 500
  lr: 0.0005
