data:
  json_path_train: "data/keypoints/public_data/train"
  json_path_val: "data/keypoints/public_data/val"
  is_public: true  # Public hoặc Private
  max_frame: 100    # Số frame tối đa
  batch_size: 4     # Kích thước batch

mlflow:
  name_id: "Thesis25"
  artifact_location: "Thesis_25_artifact"
  run_name: "Spoter_test" # or GCN_test

model:
  model_name: "gcn"  # "spoter" hoặc "gcn"
  pretrained: true      # Pretrained hay không
  finetune: false       # Finetune hay không

  pretrain_config:
    spoter:
      num_classes: 4
      hidden_dim: 72
      num_heads: 9
      encoder_layers: 6
      decoder_layers: 6
      
      

    gcn:
      in_channels: 3
      hidden_dim: 128
      num_classes: 4
      

  finetune_config:
    spoter:
      hidden_dim: 72
      num_heads: 9
      encoder_layers: 6
      decoder_layers: 6
      num_classes: 4
      

    gcn:
      in_channels: 3
      hidden_dim: 128
      num_classes: 4

train:
  num_epochs: 2
  lr: 0.0001
